### ISSUE TITLE
Sometimes  selector contains does not found element

### ISSUE THREAD

**Issue by farkroft** [Skadabr/puppeteer-selector#2]
**Step To Reproduce**

Tell us about your environment:

- Package.json:
`"puppeteer": "^1.17.0",
"puppeteer-select": "^1.0.2"`
- Platform/OS: Ubuntu 18.04
- Node Js version 8.14.0

What steps will reproduce the problem?

i have for loop, inside of it select element that contains text (pagination). Sometimes it cant find the element and throw error like this :
`Error: an element with selector: "a.page_promo_lain:contains(undefined)" not found
`

my for loop code :
`for (let activePage of pages) {
                    console.log('page sekarang ' + activePage)
                    await page.waitFor(2000)
            
                    let clickPage = await select(page).getElement(`a.page_promo_lain:contains(${activePage})`)
                    await clickPage.click()
            
                    // if promo exist
                    if (await page.$('#imgClass') !== null) {
                        // get href promo
                        const hrefs = await page.evaluate(
                            () => Array.from(document.body.querySelectorAll('#promolain > li > a'), ({ href }) => href)
                        );

                        for (let href of hrefs) {
                            const detail = await getDetails(browser, href)
                            result[`${cat}`].push(detail);
                        }
                    } else {
                        console.log('Promo not found!');
                    }
                }`

What is the expected result?

should be able to click element

What happens instead?

cant find element

**Comment by volodymyrpoliakov** [comment]
the answer in your error message
a.page_promo_lain:contains(**undefined**)
means you try to find an element with selector where you variable is **undefined**

**Comment by farkroft** [comment]
my mistake, it was I have wrong setting the flow
so it becomes undefined
