### ISSUE TITLE
extra comma

### ISSUE THREAD

**Issue by altherlex** [Skadabr/puppeteer-selector#3]
There is an extra comma which blocks debugging on Visual Studio Code

https://github.com/Skadabr/puppeteer-selector/blob/91758d8eb57b740f382c2a3afb1665dfcce48f7f/index.js#L12

https://github.com/Skadabr/puppeteer-selector/blob/91758d8eb57b740f382c2a3afb1665dfcce48f7f/index.js#L12

**Comment by volodymyrpoliakov** [comment]
fixed
